services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: UserServiceDb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  userservice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - mysql
      - elasticsearch
      - redis
    environment:
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=UserServiceDb;User=user;Password=password;
      - ElasticSearch__Uri=http://elasticsearch:9200
      - Redis__Host=redis
